foder(1,"Aktiv Musli",12.0,80.0,7.0,4.0,"Granngården",6.7,1.8,"","Aktiv Musli är baserad på ångkokt spannmål och har hög energi- och fetthalt, vilket ger högt energiutnyttjande. Den innehåller bl a majs och linfrökaka samt en påkostad vitamin och mineralblandning som anpassats till svenskt grovfoder.","Musli").
foder(2,"Aktiv Pellets",11.5,80.0,7.0,4.0,"Granngården",7.0,1.8,"","Fodret har en hög halt av energi, fett och fibrer vilket ger en skonsam men effektiv energiomsättning. Fodret innehåller en påkostad samt välbalanserad mineral- och vitaminblandning som anpassats till svenskt grovfoder.","Pellets").
foder(3,"Avel Mineral Pellets",0.0,0.0,100.0,45.0,"Granngården",0.0,2.3,"Kalciumtillskott, Avelsfodermedel","Ett smakligt och pelleterat mineralfoder som ges till unghästar och avelsston. Tack vare att mineralfodret är pelleterat så kan du alltid vara säker på att din häst får i sig rätt mängd av alla viktiga mineral-, vitamin- och spårämnen.","Pellets").
foder(4,"Avel Musli",11.0,110.0,9.0,5.0,"Granngården",10.0,1.8,"Avelsfodermedel","Avel Musli är baserad på ångkokt spannmål vilket ger ökad smältbarhet. Fodret har ett högt proteininnehåll samt en välbalanserad vitamin- och mineralblandning som passar svenskt grovfoder.","Musli").
foder(5,"Avel Pellets",10.5,110.0,9.0,5.0,"Granngården",10.5,1.8,"Avelsfodermedel","Fodret har en hög halt av protein samt innehåller en välbalanserad mineral- och vitaminblandning som passar svenskt grovfoder.","Pellets").
foder(6,"Betfor",11.3,57.0,7.0,1.1,"Nordic Sugar",5.1,6.4,"","Betfor består av ca. 70% torkad betfiber och ca 30% melass med ett naturligt innehåll av mineraler och vitaminer. Betfor har funnits i mer än 60 år och i takt med att hästsporten har vuxit har allt fler upptäckt att ett tillskott av Betfor får hästen att både prestera och må bättre","Mellasserad betfiber").
foder(7,"Competition Concentrate",12.5,134.7,25.0,6.0,"Dodson & Horrell",10.8,4.3,"Proteinfodermedel","Competition Concentrate är ett koncentrerat kompletteringsfoder med ett högt innehåll av essentiella aminosyror, vitaminer och mineraler. Produkten är mycket energirik och tillför energi från lättsmält fibrer och värmebehandlat spannmål. på grund av det koncentrerade innehållet kan Competition Conce","Musli").
foder(8,"Competition Mix",11.5,91.9,11.0,4.0,"Dodson & Horrell",8.0,2.8,"","Competition Mix är ett lättsmält foder med ett högt energiinnehåll, utvecklat till tävlingshästar/ponnyer i måttlig/hård träning.","Musli").
foder(9,"Convalescent Diet",10.0,77.6,15.0,4.0,"Dodson & Horrell",7.8,3.8,"","Convalescent Diet är speciellt sammansatt till sjuka eller skadade hästar som ska vila i kortare eller längre perioder. Stärkelsehalten är låg och fodret har ett mycket högt innehåll av lättsmält fibrer och olja. Det gynnar en bra tarmfunktion och är med till att förebygga kolik och andra matsmältni","Musli").
foder(10,"Daily Vitamins & Minerals",6.0,0.0,65.0,20.0,"Dodson & Horrell",0.0,3.3,"","Daily Vitamins & Minerals är ett brett kompletteringsfoder med vitaminer, mineraler och aminosyror av högkvalite i pillerform.","").
foder(11,"Eplus",0.0,0.0,9.0,27.0,"Pavo",0.0,0.3,"Fosfortillskott","Under ansträngande fysisk träning kan musklerna bilda mjölksyra. För att förhindra denna process ger du din häst Pavo E plus innan skadan har skett. Den kraftiga antioxidanten i Pavo E Plus hjälper musklerna att neutralisera mjölksyran i musklerna. Magnesiumtillägg hjälper musklerna att fungera bätt","Annat").
foder(12,"EquiLac Musli",12.5,94.0,12.0,4.0,"StHippolyt",7.5,3.0,"Avelsfodermedel","De sista 2 månaderna av dräktigheten och i digivningsperioden som supplement till den dagliga tillskottsfodret. Täcker stoets förändrade och utökade näringsbehov i perioden då fostret färdigutvecklas, mjölken bildas och där det ska vara energi till den nya dräktigheten.","Musli").
foder(13,"Equigard",8.5,77.0,12.0,5.0,"StHippolyt",9.1,2.4,"","Till hästar med konstaterat ämnesomsättningsproblem (EMS), Cushings Syndrom osv. Används som tillskott till utfodring med hö och där utfodring med spannmål undviks. Perfekt för att understödja en fysiologiskt balanserad viktreduktion.","Annat").
foder(14,"Equine Sensitive",10.0,68.3,13.0,4.0,"Dodson & Horrell",6.8,3.3,"Känsliga hästar","Equine Sensitive har utvecklats till hästar/ponnyer som är känsliga för foder och lätt kan få beetende, mag, muskel eller hudrelaterade problem. Equine Sensitive är ett extruderat (värmebehandlat), pelleterat foder med ett lågt energiinnehåll (kaloriinnehåll) och ett högt innehåll av vitaminer och mineraler","").
foder(15,"Extra Foderjäst",11.5,270.0,38.0,10.0,"Hippo",23.5,3.8,"Proteinfodermedel","HippoExtra Foderjäst är ett smakligt tillskott, baserat på bryggerijäst med högt innehåll av naturliga B-vitaminer och högvärdigt protein. Produkten är dessutom berikad med extra B-, C och E-vitaminer. Lämpligt fodertillskott vid exempelvis mag-tarmstörningar.","Annat").
foder(16,"Extra Lin",9.8,255.0,4.0,7.8,"Hippo",26.0,0.5,"Proteinfodermedel, Fosfortillskott","Ren naturprodukt med högt innehåll av de viktiga fettsyrorna omega 3 och 6. Bidrar till god maghälsa och gör pälsen blank. Tillför såväl protein, fibrer som energi till foderstaten. Kan även lindra allergiska besvär.","Annat").
foder(17,"Extra Olja",36.0,0.0,0.0,0.0,"Hippo",0.0,0.0,"Energitillskott","Ger ett extra koncentrerat och skonsamt energitillskott till foderstaten.","Annat").
foder(18,"Fibergy",9.0,43.4,13.5,2.0,"Dodson & Horrell",4.8,6.8,"","Fibergy är utvecklat till lättfödda hästar/ponnyer samt hästar/ponnyer med tendens till fång, Fibergy har ett mycket lågt innehåll av stärkelse (ca 1,5 %) och socker (ca. 6 %). Fibergy är en fiberblandning som består av lucern och snittad halm av god kvalite. Blandningen innehåller även mynta, som g","Annat").
foder(19,"Foal Creep Pellets",12.0,148.9,12.0,5.0,"Dodson & Horrell",12.4,2.4,"Avelsfodermedel","Foal Creep Pellets är ett lättsmält kompletteringsfoder till föl som behöver extra kalorier förutom mjölk och gräs/hö. Det är baserat på lättsmält råvaror och täcker fölets behov med de näringsämnen som inte tillförs i tillräckliga mängder från gräset och mjölken.","Pellets").
foder(21,"Foderkalk",0.0,0.0,350.0,0.0,"Hippo",0.0,0.0,"Kalciumtillskott","Tillskott av kalcium (Ca).","Annat").
foder(22,"Föl",10.0,150.0,15.0,7.0,"Krafft",15.0,2.1,"Avelsfodermedel","Kompletteringsfoder (färdigfoder) för föl och unghästar. Kan även ges till andra hästar med ökat behov av protein.","Pellets").
foder(23,"Fohlengold",12.5,94.0,16.0,5.0,"StHippolyt",7.5,3.3,"Avelsfodermedel","fölfoder som ger sunda, starka och hållbara hästar - en god start på livet. från 3:e levnadsveckan till 24 månaden. mängden anpassas i förhållande till växten.","Musli").
foder(24,"Gold Medal",15.0,144.0,45.0,15.0,"StHippolyt",9.6,3.0,"","Gold Medal innehåller alla muskelrelevanta näringsämnen och ska användas som tillägg till det sedvanliga basfodret för att understödja muskelbildningen.","Okänt").
foder(25,"Groov 125",10.0,125.0,8.0,5.0,"Krafft",12.5,1.6,"","Säkrar intaget av kvalitetsprotein och fibrer hos alla hästar. Extra högt innehåll av de viktiga aminosyrorna lysin och metionin. Lämpligt vid ökat proteinbehov.","Pellets").
foder(26,"Groov Sensitive",10.0,110.0,6.0,5.0,"Krafft",11.0,1.3,"Havrefritt","Ett havrefritt foder till alla hästar som är känsliga för havre.","Pellets").
foder(27,"Groov Special",10.0,100.0,8.0,5.0,"Krafft",10.0,1.6,"","innehåller specialbehandlad havre som kan förbättra hästens förmåga till reglering av vätskebalansen under hård ansträngning och vid mag- och tarmproblem.","Pellets").
foder(28,"Grund",11.0,80.0,7.0,4.0,"Krafft",7.3,1.8,"","Fiberrikt för vuxna hästar i lätt eller normalt arbete.","Pellets").
foder(29,"Havre Blå",9.5,75.0,10.0,3.0,"Krafft",7.9,3.3,"","Välrensad kvalitetshavre för hästar. hög och jämn volymvikt. Volymvikt innebär att havren har en hög vikt per volymenhet och att kärnorna är tunga och välfyllda. Kvalitetskontollerad både när det gäller näringsinnehåll och hygien. näringsinnehåll normalvärden.","spannmål").
foder(30,"Havre Röd",11.5,85.0,10.0,3.0,"Krafft",7.4,3.3,"","Specialhavre med hög fetthalt (fetthalten är mellan 8-10% att jämföra med 5-7% för vanlig havre) specellt framtagen för hästar av odlare med goda förutsättningar för varmluftstorkning, skörd och lagring. Kvalitetskontrollerad både när det gäller näringsinnehåll och hygien. näringsinnehåll normalvärd","spannmål").
foder(31,"HestaMix Light",10.0,80.0,14.0,5.0,"StHippolyt",8.0,2.8,"","Till alla robusta typer som islandshästar, fjordingar, haflinger, spanska hästar, tinker, shire, friser, arabhästar osv. Organiskt bundna spårämnen med hög upptaglighet säkerställer att det inte uppstår brist på spårämnen med följder som eksem och generellt dålig sundhet och låga prestationer.","Okänt").
foder(32,"HestaMix Musli",11.5,78.0,11.0,3.0,"StHippolyt",6.8,3.7,"","Till alla robusta typer som islandshästar, fjordingar, haflinger, spanska hästar, tinker, shire, friser, arabhästar osv. Organiskt bundna spårämnen med hög upptaglighet säkerställer att det inte uppstår brist på spårämnen med följder som eksem och generellt dålig sundhet och låga prestationer.","Musli").
foder(33,"Icelandic Power",11.0,63.4,15.0,7.0,"Dodson & Horrell",5.8,2.1,"","Icelandic Power är en koncentrerad Musliblandning som har ett lågt energiinnehåll (kaloriinnehåll) och ett högt innehåll av vitaminer och mineraler. Icelandic Power har ett högt innehåll av lättsmält fibrer och olja, vilket ger ökad uthållighet pga. långsam frigivning av energi.","Musli").
foder(34,"Irish Mash",10.5,92.0,4.0,5.0,"StHippolyt",8.8,0.8,"Fosfortillskott","Vid matsmältningsproblem, vid sjukdom, om hästen inte vill dricka vid tävlingar, innan transport, före och efter hårt arbete, till äldre hästar med tuggproblem, vid foderomläggning eller som belöning. är särledes välsmakande och aptitstimulerande. Stabiliserar tarmmiljön, främjar matsmältningen och","Mash").
foder(35,"Korn",12.0,76.0,1.0,3.0,"Hippo",6.3,0.3,"Fosfortillskott","Ges ofta till hästar som har svårt att sätta hull. Det bör inte ges till hästar som har lätt att bli feta, som t.ex. ponnyer. Korn har högre näringsinnehåll än havre, men färre växttrådar. Korn har en hård kärna och måste alltid krossas för att hästen ska kunna tillgodogöra sig näringen.","spannmål").
foder(36,"KwikBeet",13.3,62.5,8.0,1.0,"Dodson & Horrell",4.7,8.0,"","Ett lättsmält foder med ett högt innehåll av smältbara fibrer, anpassat till alla typer av hästar och ponnyer","Annat").
foder(37,"Liga",12.1,80.0,8.0,4.0,"Pavo",6.6,2.0,"","Kraftfoder för islandshästar och andra lättfödda hästraser","Pellets").
foder(38,"Lusern Hackad Strå",8.5,105.0,13.0,3.0,"Krafft",12.4,4.3,"Grovfoder","Lusern Hackad Strå - med en naturlig grovfoderstruktur. är rik på högklassigt protein. Kan lätt blandas med kraft- eller grovfodergivan. näringsinnehåll normalvärden.","Grovfoder").
foder(39,"Lusern Mix",9.0,65.0,9.0,2.0,"Krafft",7.3,4.5,"Grovfoder","Lusern Mix - En kombination av varmlufttorkad lusern, gräshö, melass och vegetabilisk olja. hög fiberhalt. näringsinnehåll normalvärden.","Grovfoder").
foder(40,"Lusern Pellets",8.5,105.0,13.0,3.0,"Krafft",12.4,4.3,"Grovfoder","Lusern Pellets - Varmlufttorkad lusern i pelletsform. tillför fibrer och ger smidig säkring av proteintillförseln. näringsinnehåll normalvärden.","Grovfoder").
foder(41,"Luzerne mix",10.5,82.0,12.0,3.0,"StHippolyt",7.8,4.0,"","Grovfoder av högsta kvalitet","Grovfoder").
foder(42,"Mash Sensitive",10.1,90.0,8.0,5.0,"Krafft",8.9,1.6,"","Havrefritt specialfoder med smakrika och hälsosamma råvaror som tex äpple, morot och linfrö. Passar att använda för snabbare återhämtning efter prestation eller för att få en känslig hästmage i form. Ska blandas med varmt eller kallt vatten varmt och stå i ca 10 till 15 minuter före utfodring. Rekom","Mash").
foder(43,"Mare & Youngstock",12.5,110.9,13.0,8.0,"Dodson & Horrell",8.9,1.6,"Avelsfodermedel","Mare & Youngstock är en Musli som har utvecklats vetenskapligt till avelshästar och unghästar från 1 till 3 år med fokus på optimal tillväxt, dräktiga och digivande ston samt avelshingstar som har ett måttligt till högt energibehov.","Musli").
foder(44,"Miner Blå Granulat",0.0,0.0,160.0,40.0,"Krafft",0.0,4.0,"Kalciumtillskott","Smakligt mineralfoder","Pellets").
foder(45,"Miner Blå Pellets",0.0,0.0,120.0,30.0,"Krafft",0.0,4.0,"Kalciumtillskott","Smakligt mineralfoder","Pellets").
foder(46,"Miner Grön",0.0,0.0,80.0,40.0,"Krafft",0.0,2.0,"Mineraltillskott","Välbalanserat pelleterat mineralfoder med hög smaklighet.","Pellets").
foder(47,"Miner Röd",0.0,0.0,110.0,17.0,"Krafft",0.0,6.5,"Kalciumtillskott","Smakligt välbalanserat pelleterat mineralfoder med alla vitaminer tillsatt.","Pellets").
foder(48,"Miner Vit",0.0,0.0,55.0,65.0,"Krafft",0.0,0.8,"Fosfortillskott","Smakligt välbalanserat pelleterat mineralfoder med högt fosforinnehåll.","Pellets").
foder(49,"Muskel",12.0,370.0,40.0,30.0,"Krafft",30.8,1.3,"Proteinfodermedel","Proteinrikt med lågt innehåll av stärkelse. Ger koncentrerat tillskott av kvalitetsprotein (främst potatisprotein). Extra högt innehåll av aminosyrorna lysin och metionin. Lämpligt vid akut brist, ökat behov eller risk för underskott av protein.","Pellets").
foder(50,"Musli Blå/ Sensitive",10.3,80.0,10.0,5.0,"Krafft",7.8,2.0,"","Havrefritt och ångkokt kompletteringsfoder för vuxna hästar i lätt eller normalt arbete.","Musli").
foder(51,"Musli Grön/ Protein",11.0,135.0,10.0,6.0,"Krafft",12.3,1.7,"","Ångkokt med högt innehåll av protein. höga nivåer av de viktiga aminosyrorna lysin och metionin. lämpligt vid ökat proteinbehov.","Musli").
foder(52,"Musli Röd/ High energy",12.0,105.0,10.0,5.0,"Krafft",8.8,2.0,"","Ångkokt med hög fetthalt och tillför koncentrerad energi i en form som är skonsam för musklerna.","Musli").
foder(53,"Natures Best",11.5,90.0,9.0,4.0,"Pavo",7.8,2.3,"","Strukturrik havrefri Musli med lågt sockerinnehåll. Mycket lämplig för hästar och ponnyer i underhåll eller lättare arbete. Det bästa från naturen...","Musli").
foder(54,"Original Musli",11.0,80.0,7.0,4.0,"Granngården",7.3,1.8,"","Havrefri och passar därmed även bra till heta hästar. Den är baserad på ångkokt spannmål vilket ger ökat energiutnyttjande.","Musli").
foder(55,"Original Pellets",10.5,75.0,7.0,4.0,"Granngården",7.1,1.8,"","Fodret är en välbalanserad sammansättning med hög fiberhalt. Mineral och vitaminblandningen är anpassad till svenskt grovfoder och innehåller även B-vitaminer.","Pellets").
foder(56,"Pasture Mix",10.0,68.3,8.0,3.0,"Dodson & Horrell",6.8,2.7,"","Musli till lättfödda hästar och ponnyer","Musli").
foder(57,"Pluss Protein",10.5,220.0,20.0,10.0,"Krafft",21.0,2.0,"Proteinfodermedel","tillför protein i kombination med fett och fibrer, samt vitaminer och mineraler i balanserade proportioner. Kan i rekommenderad giva samt med lämpligt grovfoder användas som enda kraftfoder där extra behov av protein finns och kan till hästar med högre energibehov kompletteras med spannmål.","Pellets").
foder(58,"Podo Grow",13.4,130.0,12.0,6.0,"Pavo",9.7,2.0,"Avelsfodermedel","för en balanserad tillväxt och optimal benutvecklingför föletunder de första viktiga åren","Pellets").
foder(59,"Podo Lac",13.1,120.0,9.0,4.0,"Pavo",9.3,2.3,"Avelsfodermedel","för dräktiga eller digivande ston!","Pellets").
foder(60,"Podo Start",12.8,140.0,10.0,7.0,"Pavo",10.9,1.4,"Avelsfodermedel","Till fölet, för en sund start!","Pellets").
foder(61,"Rider",9.0,75.0,7.0,4.0,"Krafft",8.3,1.8,"","Fiberrikt för vuxna hästar i lätt eller normalt arbete. Passar lättfödda hästar.","Pellets").
foder(62,"Slobber Mash",12.6,115.0,8.0,5.0,"Pavo",9.1,1.6,"","Den sunda och varma måltiden.","Mash").
foder(63,"SpeediBeet",12.0,42.0,7.0,1.0,"Pavo",3.5,7.0,"","Snabbsvällande flingor av betmassa","Grovfoder").
foder(64,"Sport",12.0,80.0,7.0,4.0,"Krafft",6.7,1.8,"","Rikt på fett och fibrer och tillför energi i en form som är skonsam för musklerna.","Pellets").
foder(65,"Super Condition",13.0,99.0,9.0,5.0,"StHippolyt",7.6,1.8,"","Kompletteringsfoder till träning och tävling - ger mer energi och en bättre muskelomsättning som ligger till grund för större prestationer","Okänt").
foder(66,"Triple P",13.4,110.0,9.0,4.0,"Pavo",8.3,2.3,"","högpresterande Musli för att snabbt få mycket energi.","Musli").
